Process Process-3:
Traceback (most recent call last):
  File "C:\Users\hyunoh\anaconda3\envs\spine\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\hyunoh\anaconda3\envs\spine\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\hyunoh\Documents\Codes\BMD_code\train.py", line 46, in train_fold
    train_loss = train_one_epoch(model, train_loader, optimizer, criterion, device)
  File "C:\Users\hyunoh\Documents\Codes\BMD_code\train.py", line 74, in train_one_epoch
    outputs = model(images)
  File "C:\Users\hyunoh\anaconda3\envs\spine\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\hyunoh\anaconda3\envs\spine\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\hyunoh\anaconda3\envs\spine\lib\site-packages\torchvision\models\resnet.py", line 285, in forward
    return self._forward_impl(x)
  File "C:\Users\hyunoh\anaconda3\envs\spine\lib\site-packages\torchvision\models\resnet.py", line 269, in _forward_impl
    x = self.bn1(x)
  File "C:\Users\hyunoh\anaconda3\envs\spine\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\hyunoh\anaconda3\envs\spine\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\hyunoh\anaconda3\envs\spine\lib\site-packages\torch\nn\modules\batchnorm.py", line 176, in forward
    return F.batch_norm(
  File "C:\Users\hyunoh\anaconda3\envs\spine\lib\site-packages\torch\nn\functional.py", line 2512, in batch_norm
    return torch.batch_norm(
RuntimeError: running_mean should contain 128 elements not 64
