4710030_10
<class 'str'>
L4
True
559    4710030_10
Name: ID, dtype: object
0.69
4224007_1
<class 'str'>
L4
True
428    4224007_1
Name: ID, dtype: object
0.745
2903539_1
<class 'str'>
L1
True
295    2903539_1
Name: ID, dtype: object
0.601
9761932_7
<class 'str'>
L1
True
652    9761932_7
Name: ID, dtype: object
0.519
2706227_1
<class 'str'>
L2
True
289    2706227_1
Name: ID, dtype: object
0.85
2881628
<class 'str'>
L3
True
Series([], Name: ID, dtype: object)
Traceback (most recent call last):
  File "train.py", line 127, in <module>
    train_5_fold(dataset, batch_size=16, epochs=50, learning_rate=0.0001, optimizer_type='AdamW', scheduler_type='CosineAnnealingLR', device='cuda')
  File "train.py", line 49, in train_5_fold
    train_loss = train_one_epoch(model, train_loader, optimizer, criterion, device)
  File "train.py", line 85, in train_one_epoch
    for images, labels, _ in train_loader:
  File "C:\Users\hyunoh\anaconda3\envs\spine\lib\site-packages\torch\utils\data\dataloader.py", line 630, in __next__
    data = self._next_data()
  File "C:\Users\hyunoh\anaconda3\envs\spine\lib\site-packages\torch\utils\data\dataloader.py", line 673, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\hyunoh\anaconda3\envs\spine\lib\site-packages\torch\utils\data\_utils\fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\hyunoh\anaconda3\envs\spine\lib\site-packages\torch\utils\data\_utils\fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\hyunoh\Documents\Codes\BMD_code\regression_function_classes.py", line 207, in __getitem__
    bmd = self.get_bmd(os.path.basename(img_path), ID)
  File "C:\Users\hyunoh\Documents\Codes\BMD_code\regression_function_classes.py", line 218, in get_bmd
    bmd = self.bmd_data[self.bmd_data['ID'] == ID][vert_name].values[0]
IndexError: index 0 is out of bounds for axis 0 with size 0
